const mongoose = require("mongoose");

const CreditNoteSchema = new mongoose.Schema({
  invoiceNo: { type: String },
  autoNo: { type: Number },
  invoiceDate: { type: Date },
  state: { type: String },
  stateCode: { type: String },
  documentNo: { type: String },
  issueOfDate: { type: Date },
  transportationMode: { type: String },
  vehicleNo: { type: String },
  dateOfSupply: { type: Date },
  placeOfSupply: { type: String },
  fromId: { type: mongoose.Schema.Types.ObjectId, ref: "Company" },
  fromName: { type: String },
  fromAddress: { type: String },
  fromGSTin: { type: String },
  fromState: { type: String },
  fromStateCode: { type: String },
  toId: { type: mongoose.Schema.Types.ObjectId, ref: "VendorsMaster" },
  toName: { type: String },
  toAddress: { type: String },
  toGSTin: { type: String },
  toState: { type: String },
  toStateCode: { type: String },
  invRefNo: { type: String },
  creditDate: { type: String },
  freightCharges: { type: Number },
  freightPercentage: { type: Number },
  freightChargAmt: { type: Number },
  handlingCharges: { type: Number },
  handlingPercentage: { type: Number },
  handlingChargAmt: { type: Number },
  packingCharges: { type: Number },
  packingPercentage: { type: Number },
  packingChargAmt: { type: Number },
  cashDiscount: { type: Number },
  grossAmount: { type: Number },
  discountAmount: { type: Number },
  discountedAmount: { type: Number },
  totalGSTAmount: { type: Number },
  totalPayableAmount: { type: Number },
  roundOff: { type: Number },
  active: { type: Number, default: 0 },
  created_by: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "User",
    required: true,
  },
  created_on: { type: Date, default: Date.now },
  modified_by: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "User",
  },
  modified_on: { type: Date },
  disabled_by: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "User",
  },
  disabled_on: { type: Date },
});

module.exports = mongoose.model("CreditNote", CreditNoteSchema);
