const mongoose = require("mongoose");

const EmpWagesSchema = new mongoose.Schema({
  clientId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Client",
    required: true,
  },
  siteId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "SiteDetail",
    required: true,
  },
  clientCode: { type: String, required: true },
  clientName: { type: String, required: true },
  attendanceMonth: { type: String },
  attendanceYear: { type: String },
  attendanceType: {
    type: String,
  },
  employeeId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Employees",
    required: true,
  },
  employeeName: { type: String, required: true },
  employeeCode: { type: String, required: true },
  designation: { type: String },
  basic: { type: Number, default: 0 },
  vda: { type: Number, default: 0 },
  basicVda: { type: Number, default: 0 },
  specialAllow: { type: Number, default: 0 },
  hra: { type: Number, default: 0 },
  otherAllow: { type: Number, default: 0 },
  lww: { type: Number, default: 0 },
  bonus: { type: Number, default: 0 },
  gross: { type: Number, default: 0 },
  otRate: { type: Number, default: 0 },
  fixedLeaveWages: { type: Number, default: 0 },
  perDayRate: { type: Number, default: 0 },
  fixedUniformWages: { type: Number, default: 0 },
  monthDays: { type: Number, default: 0 },
  presentDays: { type: Number, default: 0 },
  paidHoliday: { type: Number, default: 0 },
  netDays: { type: Number, default: 0 },
  otDays: { type: Number, default: 0 },
  earnedBasic: { type: Number, default: 0 },
  earnedDa: { type: Number, default: 0 },
  earnedBasicDa: { type: Number, default: 0 },
  earnedSpecialAllow: { type: Number, default: 0 },
  earnedHra: { type: Number, default: 0 },
  earnedOtherAllow: { type: Number, default: 0 },
  earnedLww: { type: Number, default: 0 },
  earnedBonus: { type: Number, default: 0 },
  earnedOtWages: { type: Number, default: 0 },
  earnedGross: { type: Number, default: 0 },
  pfWages: { type: Number, default: 0 },
  esicWages: { type: Number, default: 0 },
  deductPf: { type: Number, default: 0 },
  deductPt: { type: Number, default: 0 },
  deductEsic: { type: Number, default: 0 },
  deductLwf: { type: Number, default: 0 },
  deductOther: { type: Number, default: 0 },
  deductAdvance: { type: Number, default: 0 },
  deductLoan: { type: Number, default: 0 },
  deductUniform: { type: Number, default: 0 },
  deductId: { type: Number, default: 0 },
  deductRecovery: { type: Number, default: 0 },
  deductInstallment: { type: Number, default: 0 },
  totalDeduction: { type: Number, default: 0 },
  netTakeHome: { type: Number, default: 0 },
  arrearsPayable: { type: Number, default: 0 },
  salaryPayable: { type: Number, default: 0 },
  empPf: { type: Number, default: 0 },
  empEsic: { type: Number, default: 0 },
  empLwf: { type: Number, default: 0 },
  empGratuty: { type: Number, default: 0 },
  empCtc: { type: Number, default: 0 },
  empServiceCharges: { type: Number, default: 0 },
  empIctc: { type: Number, default: 0 },
  empGst: { type: Number, default: 0 },
  empInvoiceAmount: { type: Number, default: 0 },
  empAnyOther: { type: Number, default: 0 },
  billingType: { type: String, default: 0 },
  totalNos: { type: Number, default: 0 },
  absentDays: { type: Number, default: 0 },
  weeklyOff: { type: Number, default: 0 },
  paidLeaves: { type: Number, default: 0 },
  halfDays: { type: Number, default: 0 },
  anyOther: { type: Number, default: 0 },
  earnedLeaveWages: { type: Number, default: 0 },
  earnedUniformWages: { type: Number, default: 0 },
  earnedAnyOther: { type: Number, default: 0 },
  CGST: { type: Number, default: 0 },
  SGST: { type: Number, default: 0 },
  IGST: { type: Number, default: 0 },
  totalCL: { type: Number, default: 0 },
  totalSL: { type: Number, default: 0 },
  totalPL: { type: Number, default: 0 },
  totalHoliday: { type: Number, default: 0 },

  active: { type: Number, default: 0 },
  created_by: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "User",
    required: true,
  },
  created_on: { type: Date, default: Date.now },
  modified_by: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "User",
  },
  modified_on: { type: Date },
  disabled_by: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "User",
  },
  disabled_on: { type: Date },
});

module.exports = mongoose.model("EmpWages", EmpWagesSchema);
