const mongoose = require("mongoose");

const SiteDetailSchema = new mongoose.Schema({
  clientId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Client",
  },
  siteName: { type: String },
  workOrderNo: { type: String },
  clientCode: { type: String },
  contactPersonName: { type: String },
  address: { type: String },
  billingAddress: { type: String },
  contactNo: { type: String },
  emailId: { type: String },
  city: { type: String },
  state: { type: String },
  country: { type: String },
  locationName: { type: String },
  locationStartDate: { type: Date },
  salesPersonName: { type: String },
  salesPersonEmailId: { type: String },
  salesPersonContactNo: { type: String },
  billCycleDate: { type: String },
  status: { type: String, enum: ["Active", "Inactive"], default: "Active" },
  cgst: { type: Number },
  sgst: { type: Number },
  igst: { type: Number },
  expectedBillingAmount: { type: Number },
  daysForBilling: { type: Number },
  viewOTHours: { type: Boolean, default: false },
  attachWagesSHeet: { type: Boolean, default: false },
  roundOffAmount: { type: Boolean, default: false },
  billWithoutRank: { type: Boolean, default: false },
  nonComplianceSite: { type: Boolean, default: false },
  applyLeave: { type: Boolean, default: false },
  multiplyOTHours: { type: Boolean, default: false },
  calculateUniformDays: { type: Boolean, default: false },
  calculateEarnedGrossWithoutOT: { type: Boolean, default: false },
  pfWagesCalculatedOn: { type: String },
  ESICWagesCalculatedOn: { type: String },
  CTCCalculate: { type: String },
  wagesSettings: {
    primaryDetail: {
      srNo: { type: Boolean, default: false },
      nameOfEmployee: { type: Boolean, default: false },
      dob: { type: Boolean, default: false },
      mobileNo: { type: Boolean, default: false },
      aadhar: { type: Boolean, default: false },
      pan: { type: Boolean, default: false },
      bankName: { type: Boolean, default: false },
      acNo: { type: Boolean, default: false },
      ifsc: { type: Boolean, default: false },
      doj: { type: Boolean, default: false },
      designation: { type: Boolean, default: false },
      empCode: { type: Boolean, default: false },
      pf: { type: Boolean, default: false },
      uan: { type: Boolean, default: false },
      esicIp: { type: Boolean, default: false },
      monthDay: { type: Boolean, default: false },
      presentDays: { type: Boolean, default: false },
      absentDays: { type: Boolean, default: false },
      otDay: { type: Boolean, default: false },
      weeklyOff: { type: Boolean, default: false },
      paidLeaves: { type: Boolean, default: false },
      halfDay: { type: Boolean, default: false },
      totalSalaryDays: { type: Boolean, default: false },
    },
    fixGrossComponents: {
      basic: { type: Boolean, default: false },
      vda: { type: Boolean, default: false },
      hra: { type: Boolean, default: false },
      specialAllowance: { type: Boolean, default: false },
      otherAllowance: { type: Boolean, default: false },
      otRate: { type: Boolean, default: false },
      lww: { type: Boolean, default: false },
      bonus: { type: Boolean, default: false },
      leaveWages: { type: Boolean, default: false },
      rateOrDay: { type: Boolean, default: false },
      anyOther: { type: Boolean, default: false },
      totalGross: { type: Boolean, default: false },
    },
    earnedComponents: {
      basic: { type: Boolean, default: false },
      vda: { type: Boolean, default: false },
      hra: { type: Boolean, default: false },
      specialAllowance: { type: Boolean, default: false },
      otherAllowance: { type: Boolean, default: false },
      otAmount: { type: Boolean, default: false },
      lww: { type: Boolean, default: false },
      bonus: { type: Boolean, default: false },
      leaveWages: { type: Boolean, default: false },
      anyOther: { type: Boolean, default: false },
      totalEarned: { type: Boolean, default: false },
    },
    wagesForPf: { type: Boolean, default: false },
    wagesForEsic: { type: Boolean, default: false },
    deductions: {
      epf: { type: Boolean, default: false },
      esic: { type: Boolean, default: false },
      pt: { type: Boolean, default: false },
      mlwf: { type: Boolean, default: false },
      advance: { type: Boolean, default: false },
      loan: { type: Boolean, default: false },
      uniform: { type: Boolean, default: false },
      id: { type: Boolean, default: false },
      recovery: { type: Boolean, default: false },
      installments: { type: Boolean, default: false },
      anyother: { type: Boolean, default: false },
      totalDeduction: { type: Boolean, default: false },
    },
    netSalary: { type: Boolean, default: false },
    arrearsPayable: { type: Boolean, default: false },
    salaryPayable: { type: Boolean, default: false },
    contributions: {
      epf: { type: Boolean, default: false },
      esic: { type: Boolean, default: false },
      mlwf: { type: Boolean, default: false },
      uniform: { type: Boolean, default: false },
      subtotal: { type: Boolean, default: false },
    },
    serviceCharges: { type: Boolean, default: false },
    taxValueBeforeTax: { type: Boolean, default: false },
    cgst: { type: Boolean, default: false },
    sgst: { type: Boolean, default: false },
    igst: { type: Boolean, default: false },
    taxInvoiceValue: { type: Boolean, default: false },
  },
  active: { type: Number, default: 0 },
  created_by: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "User",
    required: true,
  },
  created_on: { type: Date, default: Date.now },
  modified_by: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "User",
  },
  modified_on: { type: Date },
  disabled_by: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "User",
  },
  disabled_on: { type: Date },
});

module.exports = mongoose.model("SiteDetail", SiteDetailSchema);
